insert into routes (img, reg_number, price, departure, destination) values ('taxi.png', 'CA 123-456',25.00, 'Stellenbosch', 'Cape Town');
insert into routes (img, reg_number, price, departure, destination) values ('taxi.png', 'CA 123-000',25.00, 'Stellenbosch', 'Kuilsriver');
insert into routes (img, reg_number, price, departure, destination) values ('taxi.png', 'CA 000-456',25.00, 'Stellenbosch', 'Cape Town');
insert into routes (img, reg_number, price, departure, destination) values ('taxi.png', 'CA 012-456',25.00, 'Kuilsriver', 'Cape Town');
insert into routes (img, reg_number, price, departure, destination) values ('taxi.png', 'CA 123-456',25.00, 'Stellenbosch', 'Kuilsriver');
insert into routes (img, reg_number, price, departure, destination) values ('taxi.png', 'CA 156345', 25.00, 'Kuilsriver','Stellenbosch');
insert into routes (img, reg_number, price, departure, destination) values ('taxi.png', 'CA 785631', 25.00, 'Stellenbosch', 'Kuilsriver');
insert into routes (img, reg_number, price, departure, destination) values ('taxi.png', 'CA 567294', 23.50, 'Cape Town','Bellville' );
insert into routes (img, reg_number, price, departure, destination) values ('taxi.png', 'CA 893042', 23.50, 'Bellville', 'Cape Town');
insert into routes (img, reg_number, price, departure, destination) values ('taxi.png', 'CA 127583', 23.50, 'Cape Town', 'Khayelitsha');
insert into routes (img, reg_number, price, departure, destination) values ('taxi.png', 'CY 123456', 23.50, 'Bellville', 'Kuilsriver');
insert into routes (img, reg_number, price, departure, destination) values ('taxi.png', 'CL 73822', 23.50, 'Stellenbosch', 'Khayelitsha');
insert into routes (img, reg_number, price, departure, destination) values ('taxi.png', 'CY 172849', 20.00, 'Bellville', 'Khayelitsha');
insert into routes (img, reg_number, price, departure, destination) values ('taxi.png', 'CY 123456', 23.50, 'Khayelitsha', 'Kuilsriver');
insert into routes (img, reg_number, price, departure, destination) values ('taxi.png', 'CAA 155674', 15.50, 'Kuilsriver', 'Mfuleni');
insert into routes (img, reg_number, price, departure, destination) values ('taxi.png', 'CAA 157683', 15.50,  'Mfuleni','Kuilsriver');