insert into routes (departure, destination) values ('Bellville', 'Stellenbosch');
insert into routes (departure, destination) values ('Cape Town', 'Bellville');
insert into routes (departure, destination) values ('Goodwood', 'Kuilsriver');
insert into routes (departure, destination) values ('Bellar', 'Bellville');
insert into routes (departure, destination) values ('Stellenbosch','Kuilsriver');
insert into routes (departure, destination) values ('Kuilsriver', 'Bellville');
insert into routes (departure, destination) values ('Claremont','Stellenbosch');
insert into routes (departure, destination) values ('Site C','Stellenbosch');
insert into routes (departure, destination) values ('Site B', 'Bellville');
insert into routes (departure, destination) values ('Makhaza','Kuilsriver');
insert into routes (departure, destination) values ('Kuilsriver','Stellenbosch');